[tool.isort]
profile = "black"
src_paths = ["scripts", "src/tb3_control"]
line_length = 119
# ignore files in .gitignore
skip_gitignore = true

[tool.black]
line-length = 119
target-version = ['py38']
include = '\.pyi?$'
# automatically ignore files in .gitignore
extend-exclude = '''
(
    \.git
    | \.vscode
    | assets
    | config
    | launch
    | models
    | rviz
    | urdf
    | worlds
)
'''

[tool.ruff]
line-length = 119
select = ["E", "F"]
ignore = ["E402", "E722", "F841"]
# automatically ignore files in .gitignore
exclude = [
    ".git",
    ".vscode",
    "assets",
    "config",
    "launch",
    "models",
    "rviz",
    "urdf",
    "worlds",
]

[tool.mypy]
python_version = 3.8
plugins = "numpy.typing.mypy_plugin"
strict = true
ignore_missing_imports = true
disallow_any_generics = false

[tool.taskipy.tasks]
fmt = "isort . && black ."
lint = "black --check . && ruff ."
mypy = "mypy ."
