agent_num: 6

field:
  # サイズを大きくすると計算が間に合わなくなるので注意
  grid_accuracy: [20, 20, 20]
  limit: [[-1, 1], [-1, 1], [-1, 1]]

agent_0:
  x_init: 0.5
  y_init: 0.5
  z_init: 0

agent_1:
  x_init: 0.5
  y_init: 0
  z_init: 0.5

agent_2:
  x_init: 0
  y_init: 0.5
  z_init: 0.5

agent_3:
  x_init: -0.5
  y_init: -0.5
  z_init: 0

agent_4:
  x_init: -0.5
  y_init: 0
  z_init: -0.5

agent_5:
  x_init: 0
  y_init: -0.5
  z_init: -0.5
