agent0:
  agent_body:
    ros__parameters:
      init_position: [0.5, 0.0]
      init_yaw: 0.0

agent1:
  agent_body:
    ros__parameters:
      init_position: [0.0, 0.5]
      init_yaw: 0.0

agent2:
  agent_body:
    ros__parameters:
      init_position: [0.5, 0.5]
      init_yaw: 0.0
